// @ts-nocheck
const Datapolicy = () => (
    <div>
        <h2>Privacy policy</h2>
        <h3 id="dsg-general-intro">
        </h3>
        <p>
            This privacy policy clarifies the nature, scope and purpose of the processing of personal data (hereinafter referred to as "data") in the context of the provision of our services and within our online services and the associated websites, functions and content as well as external online presences, such as our social media profile on (hereinafter jointly referred to as "online service"). With regard to the terms used, such as "processing" or "person responsible", we refer you to the definitions in Art. 4 of the Data Protection Basic Regulation (DSGVO).
            <b /><br />
        </p>
        <h3 id="dsg-general-controller">Responsible</h3> <p>
            <span class="tsmcontroller">Yannic Duckwitz<br />
                Breckenheimer Street, 28a<br />
                65719, Hofheim am Taunus, Hesse<br />
                E-mail address: info@ductec.de<br />
                Link to imprint: http://firemindacademy.net/impressum.html</span>
        </p> <h3 id="dsg-general-datatatype">types of processed data</h3> <p>- inventory data (e.g., personal master data, names or addresses).<br />
            - Contact data (e.g., e-mail, telephone numbers).<br />
            - Content data (e.g., text entries, photographs, videos).<br />
            - usage data (e.g., websites visited, interest in content, access times).<br />
            - Meta/communication data (e.g., device information, IP addresses).</p> <h3 id="dsg-general-datasubjects">categories of affected persons</h3> <p>visitors and users of the online service (in the following we will refer to the affected persons collectively as "users").<br />
        </p> <h3 id="dsg-general-purpose">purpose of processing</h3> <p>- Provision of the online offer, its functions and contents.<br />
            - Answering contact questions and communicating with users.<br />
            - Safety measures.<br />
            - Range measurement/Marketing<br />
            <span class="tsmcom"></span></p> <h3 id="dsg-general-terms">Terms used </h3> <p>"Personal data" means any information relating to an identified or identifiable natural person (hereinafter referred to as "data subject"); an identifiable natural person is any person who, directly or indirectly, in particular by means of association with an identifier such as a name, an identification number, location data, an online identifier (e.g., a name, an address, a telephone number, an e-mail address, an e-mail address, an e-mail address, a telephone number, an e-mail address, a telephone number, etc.) is identified as a natural person.B. cookie) or to one or more specific characteristics that are an expression of the physical, physiological, genetic, psychological, economic, cultural or social identity of that natural person.
<br />
            "processing' means any operation or set of operations which is carried out with or without the aid of automated processes and which involves personal data. The term is broad and covers practically every handling of data.
<br />
            "pseudonymisation' means the processing of personal data in such a way that the personal data can no longer be attributed to a specific data subject without the provision of additional information, provided that such additional information is kept separately and is subject to technical and organisational measures ensuring that the personal data are not attributed to an identified or identifiable natural person.
<br />
            "profiling' means any automated processing of personal data consisting of the use of such personal data to evaluate certain personal aspects relating to a natural person, in particular to analyse or predict aspects relating to the work performance, economic situation, health, personal preferences, interests, reliability, conduct, whereabouts or movements of that natural person.
<br />
            controller" means any natural or legal person, public authority, agency or body which alone or jointly with others determines the purposes and means of the processing of personal data.
<br />
            "processor' means a natural or legal person, public authority, agency or other body which processes personal data on behalf of the controller.
</p> <h3 id="dsg-general-legalbasis">Applicable legal basis</h3> <p>In accordance with art. 13 DSGVO we inform you about the legal basis of our data processing.  For users from the area of application of the data protection basic regulation (DSGVO), i.e. the EU and the EEC, the following applies, if the legal basis is not mentioned in the data protection explanation: <br />
            The legal basis for obtaining consent is Art. 6 para. 1 lit. a and Art. 7 DSGVO;<br />.
The legal basis for the processing for the fulfilment of our services and the execution of contractual measures as well as the answering of inquiries is Art. 6 para. 1 lit. b DSGVO;<br />.
The legal basis for the processing for the fulfilment of our legal obligations is Art. 6 para. 1 lit. c DSGVO;<br />
            In the event that vital interests of the data subject or another natural person necessitate the processing of personal data, Art. 6 (1) lit. d DSGVO serves as the legal basis.<br />
            The legal basis for the processing necessary for the performance of a task carried out in the public interest or in the exercise of official authority entrusted to the controller is Art. 6 para. 1 lit. e DSGVO. <br />
            The legal basis for the processing to safeguard our legitimate interests is Art. 6 para. 1 lit. f DSGVO. <br />
            The processing of data for purposes other than those for which they were collected is governed by the provisions of Art. 6 (4) DSGVO. <br />
            The processing of special categories of data (pursuant to Art. 9 para. 1 DSGVO) is governed by the provisions of Art. 9 para. 2 DSGVO. <br />
        </p> <h3 id="dsg-general-securitymeasures">Security measures</h3> <p>We take appropriate technical and organisational measures to ensure a level of protection appropriate to the risk, in accordance with the legal requirements, taking into account the state of the art, the implementation costs and the type, extent, circumstances and purposes of the processing, as well as the different probability of occurrence and severity of the risk to the rights and freedoms of natural persons.<br />
            <br />
            Measures shall include, in particular, ensuring the confidentiality, integrity and availability of data by controlling physical access to, access to, inputting, disclosure, securing and separation of data. In addition, we have established procedures to ensure the exercise of data subjects' rights, deletion of data and reaction to data threats. Furthermore, we take the protection of personal data into account as early as the development or selection of hardware, software and processes, in accordance with the principle of data protection through technology design and data protection-friendly default settings.
</p> <h3 id="dsg-general-coprocessing">Cooperation with contract processors, jointly responsible persons and third parties</h3> <p>If we disclose data to other persons and companies (contract processors, jointly responsible persons or third parties) within the scope of our processing, transfer them to them or otherwise grant them access to the data, this shall only take place on the basis of a legal permission (e.g.B. if a transfer of the data to third parties, such as payment service providers, is necessary for the performance of the contract), users have consented, a legal obligation provides for this or on the basis of our legitimate interests (e.g. when using agents, web hosts, etc.). <br />
            <br />
            Insofar as we disclose, transmit or otherwise grant access to data to other companies of our group of companies, this is done in particular for administrative purposes as a legitimate interest and beyond that on a basis corresponding to the legal requirements. <br />
        </p> <h3 id="dsg-general-thirdparty">Transmissions to third countries</h3> <p>If we process data in a third country (i.e. outside the European Union (EU), the European Economic Area (EEA) or the Swiss Confederation) or if we do so as part of the use of third-party services or disclosure, or If data is transferred to other persons or companies, this will only take place if it is done to fulfil our (pre)contractual obligations, on the basis of your consent, a legal obligation or on the basis of our legitimate interests. Subject to legal or contractual permissions, we process or leave the data in a third country only if the legal requirements are met. This means that the processing takes place e.g. on the basis of special guarantees, such as the officially recognised determination of a data protection level corresponding to the EU (e.g. for the USA by the "Privacy Shield") or observance of officially recognised special contractual obligations.</p> <h3 id="dsg-general-rightssubject">rights of the persons concerned</h3> <p>You have the right to demand confirmation as to whether relevant data will be processed and to request information about this data as well as further information and a copy of the data in accordance with the statutory provisions.<br />
            <br />
            You have the right, in accordance with the law, to request the completion of the data concerning you or the correction of the inaccurate data concerning you.
<br />
            In accordance with the statutory provisions, you have the right to demand that the relevant data be deleted immediately or, alternatively, to demand that the processing of the data be restricted in accordance with the statutory provisions.
<br />
            You have the right to demand that we receive the data concerning you that you have provided to us in accordance with the statutory provisions and to demand that it be passed on to other persons responsible. <br />
            <br />
            They also have the right, in accordance with legal requirements, to file a complaint with the competent supervisory authority.
</p> <h3 id="dsg-general-revokeconsent">right of revocation</h3> <p>You have the right to revoke your consent with effect for the future.</p> <h3 id="dsg-general-object">right of revocation</h3> <p><strong>You may object at any time to the future processing of the data concerning you in accordance with the statutory provisions. The objection can be made in particular against the processing for purposes of direct advertising.</strong></p> <h3 id="dsg-general-cookies">Cookies and right of objection for direct advertising</h3> <p>"Cookies" are small files that are stored on the user's computer. Different data can be stored within the cookies. A cookie is primarily used to store information about a user (or the device on which the cookie is stored) during or after the user's visit to an online service. Temporary cookies, or "session cookies" or "transient cookies", are cookies that are deleted after a user leaves an online offer and closes his browser. The content of a shopping basket in an online shop or a login status, for example, can be stored in such a cookie. Cookies are referred to as "permanent" or "persistent" and remain stored even after the browser is closed. For example, the login status can be saved if users visit it after several days. The interests of the users who are used for range measurement or marketing purposes can also be stored in such a cookie. Third party cookies" are cookies that are offered by providers other than the person responsible for operating the online service (otherwise, if they are only the latter's cookies, we speak of "first party cookies").
<br />
            We may use temporary and permanent cookies and explain this in the context of our privacy policy.
<br />
            If users do not wish cookies to be stored on their computer, they are asked to deactivate the corresponding option in the system settings of their browser. Stored cookies can be deleted in the system settings of the browser. The exclusion of cookies can lead to functional limitations of this online offer.<br />
            <br />
            A general objection to the use of cookies used for online marketing purposes can be raised for a large number of services, particularly in the case of tracking, via the US website <a href="http://www.aboutads.info/choices/">http://www.aboutads.info/choices/</a> or the EU website <a href="http://www.youronlinechoices.com/">http://www.youronlinechoices.com/</a>. In addition, cookies can be saved by deactivating them in the browser settings. Please note that in this case not all functions of this online offer may be available.</p> <h3 id="dsg-general-erasure">Deletion of data</h3> <p>The data processed by us will be deleted or their processing restricted in accordance with the legal requirements. Unless expressly stated in this data protection declaration, the data stored by us will be deleted as soon as they are no longer required for their intended purpose and there are no legal obligations to retain them. <br />
            <br />
            If the data are not deleted because they are required for other and legally permissible purposes, their processing will be restricted. This means that the data will be blocked and not processed for other purposes. This applies, for example, to data which must be stored for reasons of commercial or tax law.</p> <h3 id="dsg-general-changes">changes and updates to the data protection declaration</h3> <p>We kindly ask you to inform yourself regularly about the content of our data protection declaration. We will adapt the data protection declaration as soon as the changes to the data processing carried out by us make this necessary. We will inform you as soon as the changes require your cooperation (e.g. consent) or other individual notification.</p> <p></p> <h3 id="dsg-commercialpurpose">business-related processing</h3> <p></p> <p><span class="ts-muster-content">
                Additionally we process<br />
                - Contract data (for example, contract object, duration, customer category).<br />
                - Payment data (for example, bank details, payment history) <br />
                by our customers, prospective customers and business partners for the purpose of providing contractual services, service and customer care, marketing, advertising and market research.</span></p> <p></p> <h3 id="dsg-businessanalysis">business analyses and market research</h3> <p></p> <p><span class="ts-muster-content">In order to operate our business economically, to be able to recognize market tendencies, wishes of the contractual partners and users, we analyse the data available to us on business transactions, contracts, enquiries, etc., in order to be able to identify the most suitable and appropriate solutions for our customers, prospective customers and business partners. We process inventory data, communication data, contract data, payment data, usage data, metadata on the basis of Art. 6 para. 1 lit. f. DSGVO, whereby the persons concerned include contractual partners, interested parties, customers, visitors and users of our online services. <br />
                    <br />
                    The analyses are carried out for the purpose of economic evaluations, marketing and market research. We can consider the profiles of the registered users with information, e.g. about their used services. The analyses serve us to increase user friendliness, to optimise our range of services and to improve business efficiency. The analyses serve us alone and are not disclosed externally unless they are anonymous analyses with summarized values. <br />
                    <br />
                    If these analyses or profiles are person-related, they will be deleted or anonymised upon termination by the user, otherwise after two years from the conclusion of the contract. In all other respects, the macroeconomic analyses and general trend definitions will be prepared anonymously where possible.<br />
                </span></p> <p></p> <h3 id="dsg-affiliate-general">Participation in Affiliate-Partnerprograms</h3> <p></p> <p><span class="ts-muster-content">Within our online offer we set on basis of our legitimate interests (i.e. interest in the analysis, optimisation and economic operation of our online offer) pursuant to Art. 6 Para. 1 lit. f DSGVO, we use tracking measures customary in the industry insofar as these are necessary for the operation of the affiliate system. In the following, we inform the users about the technical background.<br />
                    <br />
                    The services offered by our contractual partners can also be advertised and linked on other websites (so-called affiliate links or after-buy systems if, for example, links or services of third parties are offered after a contract has been concluded). The operators of the respective websites receive a commission if users follow the affiliate links and subsequently take advantage of the offers.
<br />
                    In summary, our online offering requires us to be able to track whether users who are interested in affiliate links and/or the offers available from us subsequently perceive the offers at the instigation of the affiliate links or our online platform. For this purpose, the affiliate links and our offers are supplemented by certain values that can be set as part of the link or otherwise, e.g. in a cookie. The values include in particular the source website (referrer), time, an online identifier of the operator of the website on which the affiliate link was located, an online identifier of the respective offer, an online identifier of the user, as well as tracking specific values such as advertising material ID, partner ID and categorizations.
<br />
                    The online identifiers of the users used by us are pseudonymous values. This means that the online identifiers themselves do not contain any personal data such as names or e-mail addresses. They only help us to determine whether the same user, who clicked on an affiliate link or was interested in an offer via our online offer, perceived the offer, i.e. concluded a contract with the provider, for example. However, the online identifier is personal to the extent that the partner company and we have the online identifier together with other user data. Only in this way can the partner company tell us whether the user has taken advantage of the offer and we can, for example, pay out the bonus.
</span></p> <p></p> <h3 id="dsg-affiliate-amazon">Amazon-Partnerprogram</h3> <p></p> <p><span class="ts-muster-content">We are not responsible for any contents linked or referred to from our pages - unless we have full knowledge of illegal contents and would be able to prevent the visitors of our site fromviewing those pages (i.e. we are not responsible for the visitors of our site). DSGVO) Participant of the partner program of Amazon EU, which was conceived for the provision of a medium for websites, by means of which advertising costs can be earned by the placement of advertisements and links to Amazon.de (so-called affiliate system). I.e. as Amazon partner we earn on qualified purchases.<br /><br />
            Amazon uses cookies to track the origin of orders. Among other things, Amazon can recognize that you have clicked the partner link on this website and then purchased a product from Amazon.
<br />
            For more information on Amazon's use of data and the possibility to object, please refer to the company's privacy policy: <a target="_blank" href="https://www.amazon.de/gp/help/customer/display.html?nodeId=201909010">https://www.amazon.de/gp/help/customer/display.html?nodeId=201909010</a>.<br />
            <br />
            Note: Amazon and the Amazon logo are trademarks of Amazon.com, Inc. or one of its affiliated companies.</span></p> <p></p> <h3 id="dsg-affiliate-digistore24">Digistore24 Affiliate Program</h3> <p></p> <p><span class="ts-muster-content">We are bound by our legitimate interests (i.e. interest in the commercial operation of our online offering within the meaning of Art. 6 Para. 1 lit. f. DSGVO) Participant of the partner program of Digistore24 GmbH, St.-Godehard-Straße 32, 31139 Hildesheim, Germany, which was designed for the provision of a medium for websites, by means of which through the placement of advertisements and links to Digistore24 advertising costs can be earned (so-called affiliate system). Digistore24 uses cookies to trace the origin of the contract. Among other things, Digistore24 can recognize that you have clicked on the partner link on this website and subsequently concluded a contract with or via Digistore24.<br />.
<br />
                For more information about Digistore24's use of data and how Digistore24 can opt-out of such use, please see the company's privacy policy: <a target="_blank" href="https://www.digistore24.com/page/privacy">https://www.digistore24.com/page/privacy</a>.</span></p><p></p><h3 id="dsg-newsletter-en">Newsletter</h3><p></p><p><span class="ts-muster-content">With the following information we inform you about the contents of our newsletter as well as the registration, dispatch and statistical evaluation procedures and your rights of objection. By subscribing to our newsletter, you declare that you agree with the receipt and the described procedures.
<br />
                    Content of the newsletter: We send newsletters, e-mails and other electronic notifications containing advertising information (hereinafter "newsletter") only with the consent of the recipient or a legal permission. If the contents of the newsletter are specifically described within the scope of registration, they are decisive for the consent of the user. In addition, our newsletters contain information about our services and us.<br />
                    <br />
                    Double-Opt-In and logging: The registration to our newsletter takes place in a so-called Double-Opt-In procedure. This means that you will receive an e-mail after your registration in which you will be asked to confirm your registration. This confirmation is necessary so that nobody can register with external e-mail addresses. The registrations for the newsletter are logged in order to be able to prove the registration process according to the legal requirements. This includes the storage of the registration and confirmation time, as well as the IP address. Likewise the changes of your data stored with the Versanddienstleister are logged.<br />
                    <br />
                    Registration data: To subscribe to the newsletter, it is sufficient to enter your e-mail address. Optionally, we ask you to enter a name in the newsletter for the purpose of a personal address.<br />
                    <br />
                    The dispatch of the newsletter and the performance measurement associated with it are based on the consent of the recipients pursuant to Art. 6 para. 1 lit. a, Art. 7 DSGVO in conjunction with § 7 para. 2 no. 3 UWG or, if consent is not required, on our legitimate interests in direct marketing pursuant to Art. 6 para. 1 as per f. DSGVO in connection with § 7 Abs. 3 UWG. <br />
                    <br />
                    The registration procedure is recorded on the basis of our legitimate interests pursuant to Art. 6 para. 1 lit. f DSGVO. Our interest is directed towards the use of a user-friendly and secure newsletter system that serves our business interests as well as the expectations of the users and furthermore allows us to prove our consent.<br />
                    <br />
                    Cancellation/revocation - You can cancel the receipt of our newsletter at any time, i.e. revoke your consent. You will find a link to cancel the newsletter at the end of each newsletter. We may store the unsubscribed e-mail addresses for up to three years on the basis of our legitimate interests before deleting them in order to be able to provide evidence of a previously given consent. The processing of this data is limited to the purpose of a possible defence against claims. An individual request for deletion is possible at any time, provided that at the same time the former existence of a consenting party is proven.
</span></p><p></p><h3 id="dsg-hostingprovider">Hosting and e-mail dispatch</h3><p></p><p><span class="ts-muster-content">The hosting services used by us serve the provision of the following services: Infrastructure and platform services, computing capacity, storage space and database services, e-mail dispatch, security services and technical maintenance services which we use for the purpose of operating this online service. <br />
            <br />
            Here we, or our hosting provider, process inventory data, contact data, content data, contract data, usage data, meta data and communication data of customers, interested parties and visitors to this online service on the basis of our legitimate interests in the efficient and secure provision of this online service in accordance with Art. 6 Para. 1 lit. f DSGVO in conjunction with Art. 28 DSGVO (conclusion of an order processing contract).</span></p><p></p><h3 id="dsg-logfiles">collection of access data and logfiles</h3><p></p><p><span class="ts-muster-content">We, respectively our hosting provider, collect data on the basis of our legitimate interests in the sense of Art. 6 para. 1 lit. f. DSGVO data about each access to the server on which this service is located (so-called server log files). The access data includes the name of the website accessed, file, date and time of access, data volume transferred, notification of successful access, browser type and version, the user's operating system, referrer URL (the previously visited page), IP address and the requesting provider.
<br />
                Log file information is stored for security reasons (e.g. for the clarification of abuse or fraud actions) for the duration of maximally 7 days and deleted afterwards. Data, the further storage of which is required for evidence purposes, is excluded from deletion until the respective incident has been finally clarified.</span></p><p></p><h3 id="dsg-cdn-cloudflare">Content-Delivery-Network of Cloudflare</h3><p></p><p><span class="ts-muster-content">We use a so-called "Content Delivery Network" (CDN), offered by Cloudflare, Inc, 101 Townsend St, San Francisco, CA 94107, USA. Cloudflare is certified under the Privacy Shield Agreement and thereby offers a guarantee to comply with European data protection law (<a target="_blank" href="https://www.privacyshield.gov/participant?id=a2zt0000000GnZKAA0&amp;status=Active">https://www.privacyshield.gov/participant?id=a2zt0000000GnZKAA0&amp;status=Active</a>).<br />
                    <br />
                    A CDN is a service with the help of which contents of our online offer, especially large media files such as graphics or scripts, can be delivered faster with the help of regionally distributed servers connected via the Internet. The processing of user data is carried out solely for the above-mentioned purposes and to maintain the security and functionality of the CDN.<br />.
<br />
                    The use takes place on the basis of our legitimate interests, i.e. interest in a secure and efficient provision, analysis and optimisation of our online offer in accordance with Art. 6 Para. 1 letter f. DSGVO. <br />
                    <br />
                    Further information can be found in Cloudflare's privacy policy:&nbsp;<a target="_blank" href="https://www.cloudflare.com/security-policy">https://www.cloudflare.com/security-policy</a>.</span></p><p></p><h3 id="dsg-tracking-tagmanager">Google Tag Manager</h3><p></p><p><span class="ts-muster-content">Google Tag Manager is a solution with which we can manage so-called website tags via a single interface (and thus integrate Google Analytics as well as other Google marketing services into our online offering). The Tag Manager itself (which implements the tags) does not process any personal user data. With regard to the processing of users' personal data, reference is made to the following information on Google services. Terms of use: <a target="_blank" href="https://www.google.com/intl/de/tagmanager/use-policy.html">https://www.google.com/intl/de/tagmanager/use-policy.html</a>.<br />
                    </span></p><p></p><h3 id="dsg-ga-googleanalytics">Google Analytics</h3><p></p><p><span class="ts-muster-content">We set our own standards on the basis of our legitimate interests (i.e. interest in the analysis, optimisation and economic operation of our online offer in the sense of Art. 6 Para. 1 lit. f. DSGVO) Google Analytics, a web analysis service of Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Ireland ("Google"). Google uses cookies. The information generated by the cookie about users' use of the website is generally transmitted to and stored by Google on servers in the United States .
	<br />
                        <br />
                        Google is certified under the Privacy Shield Agreement and thereby offers a guarantee of compliance with European data protection law (<a target="_blank" href="https://www.privacyshield.gov/participant?id=a2zt000000001L5AAI&amp;status=Active">https://www.privacyshield.gov/participant?id=a2zt000000001L5AAI&amp;status=Active</a>).<br />
                        <br />
                        Google will use this information on our behalf to evaluate the use of our online services by users, to compile reports on the activities within this online service and to provide us with other services associated with the use of this online service and the Internet. Pseudonymous user profiles of the users can be created from the processed data.
<br />
                        We only use Google Analytics with IP anonymization enabled. This means that the IP address of the user is shortened by Google within member states of the European Union or in other contracting states of the Agreement on the European Economic Area. Only in exceptional cases is the full IP address transmitted to a Google server in the USA and abbreviated there.
<br />
                        The IP address transmitted by the user's browser is not merged with other Google data. Users may refuse the use of cookies by selecting the appropriate settings on their browser, however please note that if any damage occurs by the use of information presented there, only the author of the respective pages might be liable, not the one who has linked to these pages. The author intended not to use any copyrighted material for the publication or, if not possible, to indicate the copyright of the respective object.
<br />
                        Further information on the use of data by Google, setting and objection options, can be found in Google's privacy policy (<a target="_blank" href="https://policies.google.com/privacy">https://policies.google.com/privacy</a>) as well as in the settings for the display of advertising by Google <a target="_blank" href="https://adssettings.google.com/authenticated">(https://adssettings.google.com/authenticated</a>).<br />
                        <br />
                        Users' personal data will be deleted or anonymized after 14 months. </span></p><p></p><h3 id="dsg-ga-universal">Google Universal Analytics</h3><p></p><p><span class="ts-muster-content">We use Google Analytics in the form of "<a target="_blank" href="https://support.google.com/analytics/answer/2790010?hl=de&amp;ref_topic=6010376">Universal-Analytics</a>". "Universal Analytics" refers to a Google Analytics procedure in which user analysis is performed on the basis of a pseudonymous user ID, thereby creating a pseudonymous profile of the user with information from the use of various devices (so-called "cross-device tracking").</span></p><p></p><h3 id="dsg-ga-audiences">Target grouping with Google Analytics</h3><p></p><p><span class="ts-muster-content">We use Google Analytics in order to display the ads placed by Google and its partners within advertising services only to users who have also shown an interest in our online offering or who have certain features (e.g., the ability to see the content of Google's website, the ability to track the content of Google's website, the ability of Google to track the content of Google's advertising services, and the ability of Google to track the content of Google's advertising services).B. interests in certain topics or products which are determined on the basis of the websites visited) which we transmit to Google (so-called "remarketing" or "Google Analytics Audiences"). With the help of remarketing audiences, we also want to ensure that our ads match the potential interest of users.
</span></p><p></p><h3 id="dsg-tracking-adsense-personalized">Google Adsense with personalized ads</h3><p></p><p><span class="ts-muster-content">We use our online content on the basis of our legitimate interests (i.e. interest in the analysis, optimization and economical operation of our online content in the sense of Art. 6 Para. 1 lit. f. DSGVO) the services of Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Ireland ("Google").
<br />
            Google is certified under the Privacy Shield Agreement and thereby offers a guarantee of compliance with European data protection law (<a target="_blank" href="https://www.privacyshield.gov/participant?id=a2zt000000001L5AAI&amp;status=Active">https://www.privacyshield.gov/participant?id=a2zt000000001L5AAI&amp;status=Active</a>).<br />
            <br />
            We use the AdSense service to display ads on our website and receive a fee for displaying or otherwise using them. For these purposes, usage data such as the click on an ad and the IP address of the user is processed, whereby the IP address is shortened by the last two digits. For this reason, the processing of user data is pseudonymised. <br />
            <br />
            We use Adsense with personalized ads. Google uses the websites or apps users visit and the user profiles they create to determine their interests. Advertisers use this information to tailor their campaigns to these interests, which is beneficial to both users and advertisers. For Google, ads are personalized when collected or known data determines or influences ad selection. This includes, but is not limited to, past searches, activities, site visits, app usage, demographics, and location information. Specifically, this includes demographic targeting, targeting to interest categories, remarketing, targeting to match lists, and targeting lists uploaded to DoubleClick Bid Manager or Campaign Manager.
<br />
            Further information on the use of data by Google, setting and objection options, can be found in Google's privacy policy (<a target="_blank" href="https://policies.google.com/technologies/ads">https://policies.google.com/technologies/ads</a>) as well as in the settings for the display of advertising by Google <a target="_blank" href="https://adssettings.google.com/authenticated">(https://adssettings.google.com/authenticated</a>).<br />
        </span></p><p></p><h3 id="dsg-tracking-adsense-nonpersonalized">Google Adsense with non-personalized ads</h3><p></p><p><span class="ts-muster-content">We use our online content on the basis of our legitimate interests (i.e. interest in the analysis, optimization and economic operation of our online content in the sense of Art. 6 Para. 1 lit. f. DSGVO) the services of Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Ireland ("Google").
<br />
            Google is certified under the Privacy Shield Agreement and thereby offers a guarantee of compliance with European data protection law (https://www.privacyshield.gov/participant?id=a2zt000000001L5AAI&amp;status=Active).<br />
            <br />
            We use the AdSense service to display ads on our website and receive a fee for displaying or otherwise using them. For these purposes, usage data such as the click on an ad and the IP address of the user is processed, whereby the IP address is shortened by the last two digits. For this reason, the processing of user data is pseudonymised. <br />
            <br />
            We use Adsense with non-personalized displays. The ads are not displayed on the basis of user profiles. Non-personalized ads are not based on past user behavior. Targeting uses contextual information, including rough (e.g., local) geographic targeting based on current location, content on the current website or app, and current keywords. Google prohibits all personalized targeting, including demographic targeting and targeting based on user lists.
<br />
            Further information on the use of data by Google, setting and objection options can be found in Google's privacy policy (<a target="_blank" href="https://policies.google.com/technologies/ads">https://policies.google.com/technologies/ads</a>) and in the settings for the display of advertising by Google <a target="_blank" href="https://adssettings.google.com/authenticated">(https://adssettings.google.com/authenticated</a>).</span></p><p></p><h3 id="dsg-tracking-doubleclick">Google Doubleclick</h3><p></p><p><span class="ts-muster-content">We use our website on the basis of our legitimate interests (i.e. interest in the analysis, optimization and economic operation of our online offering in the sense of Art. 6 Para. 1 lit. f. DSGVO) the services of Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Ireland ("Google").
<br />
                Google is certified under the Privacy Shield Agreement and thereby offers a guarantee of compliance with European data protection law (https://www.privacyshield.gov/participant?id=a2zt000000001L5AAI&amp;status=Active).<br />
                <br />
                We use the online marketing method Google "Doubleclick" to place ads in the Google advertising network (e.g., in search results, in videos, on websites, etc.). Double Click is characterized by the fact that ads are displayed in real time based on users' suspected interests. This allows us to display ads for and within our online offering in a more targeted manner to present users only with ads that potentially match their interests. If, for example, a user is shown ads for products in which he or she is interested in other online offers, this is referred to as "remarketing".
For these purposes, when you visit our and other websites on which the Google Advertising Network is active, Google executes a Google code directly and incorporates (re)marketing tags (invisible graphics or code, also known as "web beacons") into the website. With their help, an individual cookie, i.e. a small file, is stored on the user's device (comparable technologies can also be used instead of cookies). This file records which websites the user visits, what content he is interested in and what offers the user has clicked, as well as technical information on the browser and operating system, referring websites, visit times and other information on the use of the online service. <br />
                <br />
                The IP address of the user is also recorded, whereby this is shortened within member states of the European Union or in other contracting states of the Agreement on the European Economic Area and only in exceptional cases is it transmitted in full to a Google server in the USA and shortened there. Google may also link the above information to such information from other sources. If the user subsequently visits other websites, advertisements tailored to the user's profile may be displayed according to the user's presumed interests.
<br />
                User data is processed pseudonymously within the Google advertising network. This means, for example, that Google does not store and process the user's name or e-mail address, but processes the relevant data cookie-related within pseudonymous user profiles. This means that, from Google's point of view, the ads are not administered and displayed for a specifically identified person, but for the cookie holder, regardless of who this cookie holder is. This does not apply if a user has expressly permitted Google to process the data without this pseudonymisation. The information collected about users by Google Marketing Services is transmitted to Google and stored on Google's servers in the United States.
<br />
                Further information on Google's use of data, setting and objection options can be found in Google's privacy policy (<a target="_blank" href="https://policies.google.com/technologies/ads">https://policies.google.com/technologies/ads</a>) and in the settings for the display of advertising by Google <a target="_blank" href="https://adssettings.google.com/authenticated">(https://adssettings.google.com/authenticated</a>).</span></p><p></p><h3 id="dsg-facebook-pixel">Facebook-Pixel, Custom Audiences and Facebook-Conversion</h3><p></p><p><span class="ts-muster-content">Within our online offer, due to our legitimate interests in the analysis, optimization and economic operation of our online offer and for these purposes, the so-called "website" is used for the purpose of providing you with the information you need. "Facebook pixel" of the social network Facebook, which is operated by Facebook Inc., 1 Hacker Way, Menlo Park, CA 94025, USA, or, if you are resident in the EU, Facebook Ireland Ltd., 4 Grand Canal Square, Grand Canal Harbour, Dublin 2, Ireland ("Facebook").
<br />
                    Facebook is certified under the Privacy Shield Agreement and thus provides a guarantee of compliance with European data protection law (<a target="_blank" href="https://www.privacyshield.gov/participant?id=a2zt0000000GnywAAC&amp;status=Active">https://www.privacyshield.gov/participant?id=a2zt0000000GnywAAC&amp;status=Active</a>).<br />
                    <br />
                    With the help of the Facebook pixel, Facebook is on the one hand able to determine the visitors of our online offer as a target group for the presentation of ads (so-called "Facebook ads"). Accordingly, we use the Facebook pixel to display the Facebook ads placed by us only to Facebook users who have shown an interest in our online offering or who have certain characteristics (e.g. interests in certain topics or products that are determined on the basis of the websites visited) that we transmit to Facebook (so-called "custom audiences"). Using Facebook pixels, we also want to ensure that our Facebook ads match the potential interest of users and are not annoying. Using Facebook pixels, we can also track the effectiveness of Facebook ads for statistical and market research purposes by seeing if users were redirected to our website after clicking on a Facebook ad ("conversion").
<br />
                    Facebook processes the data in accordance with the Facebook Data Usage Policy.
Accordingly, general information about the presentation of Facebook ads in Facebook's data usage policy is provided in the following manner: "Facebook:&nbsp;<a target="_blank" href="https://www.facebook.com/policy">https://www.facebook.com/policy</a>. For specific information and details about Facebook pixels and how they work, please visit the Facebook help section: <a target="_blank" href="https://www.facebook.com/business/help/651294705016616">https://www.facebook.com/business/help/651294705016616</a>.<br />
                    <br />
                    You may opt out of Facebook pixel collection and use of your information to display Facebook ads. To set what types of ads you see within Facebook, you can go to the page set up by Facebook and follow the instructions on the settings for usage-based ads there:&nbsp;<a target="_blank" href="https://www.facebook.com/settings?tab=ads">https://www.facebook.com/settings?tab=ads</a>. The settings are platform-independent, i.e. they are applied to all devices, such as desktop computers or mobile devices.<br />
                    <br />
                    You may also use cookies to measure reach and for advertising purposes via the Network Advertising Initiative deactivation page (<a target="_blank" href="http://optout.networkadvertising.org/">http://optout.networkadvertising.org/</a>) and additionally via the US website&nbsp;(<a target="_blank" href="http://www.aboutads.info/choices">http://www.aboutads.info/choices</a>)&nbsp;or the European website&nbsp;(<a target="_blank" href="http://www.youronlinechoices.com/uk/your-ad-choices/">http://www.youronlinechoices.com/uk/your-ad-choices/</a>).</span></p><p></p><h3 id="dsg-socialmedia">Online presences in social media</h3><p></p><p><span class="ts-muster-content">We maintain online presences within social networks and platforms in order to be able to communicate with the customers, interested parties and users active there and to inform them about our services.
<br />
                        We would like to point out that user data may be processed outside the European Union. This could result in risks for users, e.g. because it could make it more difficult to enforce users' rights. With regard to US providers that are certified under the Privacy Shield, we would like to point out that by doing so they commit themselves to comply with the EU data protection standards.<br />
                        <br />
                        Furthermore, user data is usually processed for market research and advertising purposes. For example, user profiles can be created on the basis of user behaviour and the resulting interests of users. The user profiles can in turn be used, for example, to place advertisements inside and outside the platforms that presumably correspond to the interests of the users. For these purposes, cookies are usually stored on the user's computer in which the user's usage behaviour and interests are stored. Furthermore, data can also be stored in the user profiles independently of the devices used by the users (especially if the users are members of the respective platforms and are logged on to them).
<br />
                        The processing of users' personal data is carried out on the basis of our legitimate interests in effective information for users and communication with users pursuant to Art. 6 Para. 1 lit. f. DSGVO. If the users are asked by the respective providers of the platforms for their consent to the aforementioned data processing, the legal basis for the processing is Art. 6 Para. 1 lit. a., Art. 7 DSGVO.<br />.
<br />
                        For a detailed representation of the respective processing and the possibilities of objection (Opt-Out), we refer to the following linked information of the providers.<br />
                        <br />
                        Also in the case of requests for information and the assertion of user rights, we point out that these can be asserted most effectively with the providers. Only the providers have access to the data of the users and can directly take appropriate measures and give information. Should you nevertheless need help, then you can contact us.
<br />
                        <br />
                        - Facebook, -Pages, -Groups, (Facebook Ireland Ltd., 4 Grand Canal Square, Grand Canal Harbour, Dublin 2, Ireland) on the basis of a <a target="_blank" href="https://www.facebook.com/legal/terms/page_controller_addendum">Personal Data Sharing Agreement</a> - Privacy Statement: <a target="_blank" href="https://www.facebook.com/about/privacy/">https://www.facebook.com/about/privacy/</a>, specifically for Pages: <a target="_blank" href="https://www.facebook.com/legal/terms/information_about_page_insights_data">https://www.facebook.com/legal/terms/information_about_page_insights_data</a> , Opt-Out: <a target="_blank" href="https://www.facebook.com/settings?tab=ads">https://www.facebook.com/settings?tab=ads</a> and <a target="_blank" href="http://www.youronlinechoices.com">http://www.youronlinechoices.com</a>, Privacy Shield: <a target="_blank" href="https://www.privacyshield.gov/participant?id=a2zt0000000GnywAAC&amp;status=Active">https://www.privacyshield.gov/participant?id=a2zt0000000GnywAAC&amp;status=Active</a>.<br />
                        <br />
                        - Google/ YouTube (Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA) - Privacy Policy: &nbsp;<a target="_blank" href="https://policies.google.com/privacy">https://policies.google.com/privacy</a>, Opt-Out: <a target="_blank" href="https://adssettings.google.com/authenticated">https://adssettings.google.com/authenticated</a>, Privacy Shield: <a target="_blank" href="https://www.privacyshield.gov/participant?id=a2zt000000001L5AAI&amp;status=Active">https://www.privacyshield.gov/participant?id=a2zt0000001L5AAI&amp;status=Active</a>.<br />
                        <br />
                        - Instagram (Instagram Inc., 1601 Willow Road, Menlo Park, CA, 94025, USA) - Privacy Statement / Opt-Out: <a target="_blank" href="http://instagram.com/about/legal/privacy/">http://instagram.com/about/legal/privacy/</a>.<br />
                        <br />
                        - Twitter (Twitter Inc., 1355 Market Street, Suite 900, San Francisco, CA 94103, USA) - Privacy Policy: <a target="_blank" href="https://twitter.com/de/privacy">https://twitter.com/de/privacy</a>, Opt-Out: <a target="_blank" href="https://twitter.com/personalization">https://twitter.com/personalization</a>, Privacy Shield: <a target="_blank" href="https://www.privacyshield.gov/participant?id=a2zt0000000TORzAAO&amp;status=Active">https://www.privacyshield.gov/participant?id=a2zt0000000TORzAAO&amp;status=Active</a>.<br />
                        <br />
                        - Pinterest (Pinterest Inc., 635 High Street, Palo Alto, CA, 94301, USA) - Privacy Statement / Opt-Out: <a target="_blank" href="https://about.pinterest.com/de/privacy-policy">https://about.pinterest.com/de/privacy-policy</a>.<br />
                        <br />
                        - LinkedIn (LinkedIn Ireland Unlimited Company Wilton Place, Dublin 2, Ireland) - Privacy Statement <a target="_blank" href="https://www.linkedin.com/legal/privacy-policy">https://www.linkedin.com/legal/privacy-policy</a> , Opt-Out: <a target="_blank" href="https://www.linkedin.com/psettings/guest-controls/retargeting-opt-out">https://www.linkedin.com/psettings/guest-controls/retargeting-opt-out</a>, Privacy Shield:&nbsp;<a target="_blank" href="https://www.privacyshield.gov/participant?id=a2zt0000000L0UZAA0&amp;status=Active">https://www.privacyshield.gov/participant?id=a2zt0000000L0UZAA0&amp;status=Active</a>.<br />
                        <br />
                        - Xing (XING AG, Dammtorstraße 29-32, 20354 Hamburg, Germany) - Privacy Statement / Opt-Out: <a target="_blank" href="https://privacy.xing.com/de/datenschutzerklaerung">https://privacy.xing.com/de/datenschutzerklaerung</a>.<br />
                        <br />
                        - Wakalet (Wakelet Limited, 76 Quay Street, Manchester, M3 4PR, United Kingdom) - Privacy Statement / Opt-Out: <a target="_blank" href="https://wakelet.com/privacy.html">https://wakelet.com/privacy.html</a>.<br />
                        <br />
                        - Soundcloud (SoundCloud Limited, Rheinsberger Str. 76/77, 10115 Berlin, Germany) - Privacy Policy / Opt-Out: <a target="_blank" href="https://soundcloud.com/pages/privacy">https://soundcloud.com/pages/privacy</a>.</span></p><p></p><h3 id="dsg-thirdparty-introduction">Integration of services and contents of third parties</h3><p></p><p><span class="ts-muster-content">Within our online offer, we place our trust in the integration of third parties on the basis of our legitimate interests (i.e. interest in the analysis, optimisation and economic operation of our online offer in the sense of Art. 6 Par. 1 lit. f. DSGVO) content or service offers from third parties in order to integrate their content and services, such as videos or fonts (hereinafter uniformly referred to as "content"). <br />
                            <br />
                            This always presupposes that the third-party providers of this content perceive the IP address of the user, since they would not be able to send the content to their browser without the IP address. The IP address is therefore required for the presentation of this content. We make every effort to use only those contents whose respective providers only use the IP address to deliver the contents. Third-party providers may also use so-called pixel tags (invisible graphs).
The "pixel tags" can be used to evaluate information such as visitor traffic on the pages of this website. The pseudonymous information may also be stored in cookies on the user's device and may include technical information about the browser and operating system, referring web pages, visit times and other information about the use of our website, as well as may be linked to such information from other sources.</span></p><p></p><h3 id="dsg-thirdparty-youtube">Youtube</h3><p></p><p><span class="ts-muster-content">We include videos from the YouTube platform of Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Ireland. Privacy policy: <a target="_blank" href="https://www.google.com/policies/privacy/">https://www.google.com/policies/privacy/</a>, Opt-Out: <a target="_blank" href="https://adssettings.google.com/authenticated">https://adssettings.google.com/authenticated</a>.</span></p><p><p></p><h3 id="dsg-thirdparty-googlefonts">Google Fonts</h3><p></p><p><span class="ts-muster-content">We include the fonts ("Google Fonts") of Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Ireland. According to Google, the user data is used solely for the purpose of displaying the fonts in the user's browser. The integration takes place on the basis of our legitimate interests in a technically secure, maintenance-free and efficient use of fonts, their uniform presentation and consideration of possible licensing restrictions for their integration. Privacy policy: <a target="_blank" href="https://www.google.com/policies/privacy/">https://www.google.com/policies/privacy/</a>.</span></p><p></p><h3 id="dsg-thirdparty-googlerecaptcha">Google ReCaptcha</h3><p></p><p><span class="ts-muster-content">We bind the function to recognize bots, e.g. to the following extent: "We bind the function to recognize bots, e.g. to the following extent: "Bots", "Bots", "Bots", "Bots", "Bots", "Bots", "Bots", "Bots", "Bots", "Bots", "Bots", "Bots", "Bots", "Bots", "Bots,", "Bots,", "her.B. for entries in online forms ("ReCaptcha") of the provider GGoogle Ireland Limited, Gordon House, Barrow Street, Dublin 4, Ireland. Privacy Policy: <a target="_blank" href="https://www.google.com/policies/privacy/">https://www.google.com/policies/privacy/</a>, Opt-Out: <a target="_blank" href="https://adssettings.google.com/authenticated">https://adssettings.google.com/authenticated</a>.</span></p><p></p><h3 id="dsg-thirdparty-twitter">Twitter</h3><p></p><p><span class="ts-muster-content">Within our online services, functions and contents of the Twitter service, offered by Twitter Inc., 1355 Market Street, Suite 900, San Francisco, CA 94103, USA. This may include, for example, content such as images, videos or texts and buttons with which users can share content from this online service within Twitter.<br />
            If the users are members of the Twitter platform, Twitter can assign the call of the above-mentioned contents and functions to the profiles of the users there. Twitter is certified under the Privacy Shield Agreement and thus offers a guarantee of compliance with European data protection law (<a target="_blank" href="https://www.privacyshield.gov/participant?id=a2zt0000000TORzAAO&amp;status=Active">https://www.privacyshield.gov/participant?id=a2zt0000000TORzAAO&amp;status=Active</a>). Privacy policy: <a target="_blank" href="https://twitter.com/de/privacy">https://twitter.com/de/privacy</a>, Opt-Out: <a target="_blank" href="https://twitter.com/personalization">https://twitter.com/personalization</a>.</span></p><a href="https://datenschutz-generator.de" class="dsg1-6" rel="nofollow" target="_blank">Created with Datenschutz-Generator.de by RA Dr. Thomas Schwenke</a>
        </p></div>);
export default Datapolicy;